export const CHALLENGES = [
  {
    id: 'starter_streak',
    name: 'Starter Streak',
    description: 'Complete 5 workouts in 7 days',
    goal: 5,
    duration: 7,
    type: 'workouts',
    difficulty: 'easy',
    icon: 'flame',
    premium: true,
  },
  {
    id: 'consistency_king',
    name: 'Consistency King',
    description: 'Complete 12 workouts in 30 days',
    goal: 12,
    duration: 30,
    type: 'workouts',
    difficulty: 'medium',
    icon: 'crown',
    premium: true,
  },
  {
    id: 'thirty_in_thirty',
    name: '30 in 30',
    description: 'Complete 30 workouts in 30 days',
    goal: 30,
    duration: 30,
    type: 'workouts',
    difficulty: 'hard',
    icon: 'fire',
    premium: true,
  },
  {
    id: 'minute_master',
    name: 'Minute Master',
    description: 'Train for 300 total minutes in 30 days',
    goal: 300,
    duration: 30,
    type: 'minutes',
    difficulty: 'medium',
    icon: 'clock',
    premium: true,
  },
  {
    id: 'habit_machine',
    name: 'Habit Machine',
    description: 'Hit all daily habits for 7 days straight',
    goal: 7,
    duration: 7,
    type: 'habits_perfect',
    difficulty: 'medium',
    icon: 'check',
    premium: true,
  },
  {
    id: 'iron_will',
    name: 'Iron Will',
    description: 'Work out every day for 14 days straight',
    goal: 14,
    duration: 14,
    type: 'streak',
    difficulty: 'hard',
    icon: 'shield',
    premium: true,
  },
];
